### ISSUE TITLE
Crashed on directory change

### ISSUE THREAD

**Issue by thperez1972** [xLightsSequencer/xLights#4277]
Xlights 2024.01 crashes on an intel macbook pro when the directory is changed (permanent and temporary) to a new directory. But if I change permanently, Xlights will reopen on the new directory. 

1.4 GHz Quad-Core Intel Core i5
Intel Iris Plus Graphics 645 1536 MB
8 GB 2133 MHz LPDDR3
macOS Ventura Version 13.5.1 (22G90)

**To Reproduce**
When I click ok to change directories, the app crashes.

[xLights_dbgrpt-16455-20240118T130814.zip](https://github.com/xLightsSequencer/xLights/files/13980798/xLights_dbgrpt-16455-20240118T130814.zip)

**Comment by cybercop23** [comment]
2nd that. Changed to Base folder from my Christmans folder and that switched okay, but when I restored to permanent it crashed. I'm on Mac M2.

**Comment by AzGilrock** [comment]
I highly doubt that whether the directory change is temporary or permanent has anything to do with root cause for this.

**Comment by thperez1972** [comment]
> I highly doubt that whether the directory change is temporary or permanent has anything to do with root cause for this.

You're right. I'm sure they would prefer more vagueness in their issue reports.

**Comment by AzGilrock** [comment]
> > I highly doubt that whether the directory change is temporary or permanent has anything to do with root cause for this.
> 
> You're right. I'm sure they would prefer more vagueness in their issue reports.

What do mean they?  I'm a main developer and I'm adding my opinion based on viewing the code for the last 15 minutes.  We know changing directories can cause crashes and I'm saying that to indicate we need an open mind that it might not be just those conditions.  Why are you reacting like your feelings got hurt?

**Comment by cybercop23** [comment]
True story. Started xLights... Temp switch to Base folder... ok... Switch back to show.. BHAM....


`2024-01-18 15:35:55,036 8647516288 log_base [DEBUG] Special options file not found at /Volumes/documents/Alex/2023/Christmas-3D/special.options
2024-01-18 15:35:55,036 8647516288 log_base [DEBUG] Show directory set to : /Volumes/documents/Alex/2023/Christmas-3D.
2024-01-18 15:35:55,037 8647516288 log_base [DEBUG] Loading networks.
2024-01-18 15:35:55,037 8647516288 log_base [CRIT] Crashed: Fatal exception occurred.
2024-01-18 15:36:05,639 8647516288 log_base [CRIT] xLights version 2024.01
Time: 2024-01-18T15:36:05
`

**Comment by AzGilrock** [comment]
The crash posted here happened inside the Load function for the OutputManager.  I'd permanently switch to that folder then restart xLights and do a Tools -> Package Log Files so we can see what clean output looks like in that folder.

**Comment by cybercop23** [comment]
https://youtu.be/Hio8BrSoZ54

**Comment by thperez1972** [comment]
> > > I highly doubt that whether the directory change is temporary or permanent has anything to do with root cause for this.
> > 
> > 
> > You're right. I'm sure they would prefer more vagueness in their issue reports.
> 
> What do you mean "they"? I'm a main developer and I'm adding my opinion based on viewing the code for the last 15 minutes. We know changing directories can cause crashes and I'm saying that to indicate we need an open mind that it might not be just those conditions. Why are you reacting like your feelings got hurt?

My feelings aren't hurt at all. My reply was in line with your post. While I have no doubt your programming knowledge and the programming knowledge of many others here far exceeds my programming knowledge, I do know that the code being executed when one button is clicked cannot be the same code executed when the other button is clicked. So when the bug report asked me to explain how to reproduce the error, I listed what I did to reproduce the error. To me and my novice programming abilities, the fact it crashed on both types of directory changes would at least hint that any issue might be somewhere other than in the code each executes exclusively. That seemed to me to be a relevant detail to include. 

So when I see a comment that appears to be sarcastic and offers no context in explaining what the problem could be, I tend to respond in kind. I do have an open mind. That's why I posted the bug report. 

So if you're one of the people responsible for keeping xlights up and running, thank you. I like your work. So do a lot of people who watch my shows. I won't apologize for replying to a contextless seemingly snarky comment with a snarky reply. But I will try to remember your name and recognize there may be unwritten context in your posts.

**Comment by AzGilrock** [comment]
> True story. Started xLights... Temp switch to Base folder... ok... Switch back to show.. BHAM....
> 
> `2024-01-18 15:35:55,036 8647516288 log_base [DEBUG] Special options file not found at /Volumes/documents/Alex/2023/Christmas-3D/special.options 2024-01-18 15:35:55,036 8647516288 log_base [DEBUG] Show directory set to : /Volumes/documents/Alex/2023/Christmas-3D. 2024-01-18 15:35:55,037 8647516288 log_base [DEBUG] Loading networks. 2024-01-18 15:35:55,037 8647516288 log_base [CRIT] Crashed: Fatal exception occurred. 2024-01-18 15:36:05,639 8647516288 log_base [CRIT] xLights version 2024.01 Time: 2024-01-18T15:36:05 `

Yeah so your saying yours happened when coming back.  That's different.  The common thing is switching folders.  Over the years we've always run into problems dealing with switching show folders.

**Comment by AzGilrock** [comment]
Yeah the only active developer that's been around longer than me is Dan.  And when I want to be "snarky" it will be more obvious.  When I said that I had just spent time looking up what the code does different for "temporary" vs "permanent" and I didn't think that was root cause probably more of a coincendence but hey I don't care if I'm wrong I just want to see things fixed.  Try switching 5 times and see if its consistent.  Try switching to other folders to see if its isolated to something in that particular folder.  That's the kinda stuff we have to do to isolate an issue.  Another thing that happens is people get a crash on a new version and we immediately see posts on Facebook saying don't use the new version its got crashing issues when the reality usually is nothing in the new version is causing the crash.

**Comment by thperez1972** [comment]
Directory a to b temp - crash - reopened in aa to b temp - crash - reopened in aa to b permanent - crash - reopened in bB to a temp - crash - reopened in bB to a permanent - crash - opened in aI guess the program is crashing somewhere after it has assigned the permanent directory. On a temp change, the permanent directory does not change so it opens in the old one. But it at least remembers the new one on a permanent change. So xlights will open on both folders. It just won’t change to the other one. Which is different than the other posts in here where they were successful in the temp change and had crashes upon restoring permanent. On Jan 18, 2024, at 2:55 PM, Gil Jones ***@***.***> wrote:﻿
Yeah the only active developer that's been around longer than me is Dan.  And when I want to be "snarky" it will be more obvious.  When I said that I had just spent time looking up what the code does different for "temporary" vs "permanent" and I didn't think that was root cause probably more of a coincendence but hey I don't care if I'm wrong I just want to see things fixed.  Try switching 5 times and see if its consistent.  Try switching to other folders to see if its isolated to something in that particular folder.  That's the kinda stuff we have to do to isolate an issue.  Another thing that happens is people get a crash on a new version and we immediately see posts on Facebook saying don't use the new version its got crashing issues when the reality usually is nothing in the new version is causing the crash.

**Comment by computergeek1507** [comment]
I think I fixed it, try the next nightly or build whenever it comes out d97e057d2fff1462871437c40da005a85e82b443

**Comment by cybercop23** [comment]
Fixed in 2024.2. Please close

**Comment by AzGilrock** [comment]
I’ve heard reports of the latest version still crashing when changing show folders but it could be for a different reason

**Comment by cybercop23** [comment]
IDK.. I'm on latest on Mac using TestFlight and no issues since Scott made the change. Haven't seen/heard anything else on zoom about this to yeah.. maybe a totally diff issue. But I fell confident that the originally reported issue was fixed.

**Comment by AzGilrock** [comment]
If Ron Howard says it’s crashing its crashing

**Comment by AzGilrock** [comment]
So I just caught this crash.  I had just changed Show folders and then tried to create a new sequence.  After hitting the Done button on the New Sequence dialog xLights crashed loading the Perspectives.  Digging down into the function call stack it did not look like it was our code it seems to be a crash inside wxWidgets wxAuiManager.

<img width="1422" alt="Screenshot 2024-01-29 at 9 37 17 AM" src="https://github.com/xLightsSequencer/xLights/assets/2024669/8ffb9138-1eaf-47f4-91aa-8947dd6e40c5">

**Comment by derwin12** [comment]
Anyone know if this might be just a Mac issue or perhaps windows as well?

**Comment by cybercop23** [comment]
I'm on latest Mac using TestFlight.. no issues switching dirs.

**Comment by cybercop23** [comment]
Looks like the same issue just happend in #4324 for Clyde and that's on Windows.

**Comment by cybercop23** [comment]
@AzGilrock can we move and track this under #4324 since that's the same behaviour you saw and Clyde had today? The original one here was fixed by Scott.
