### ISSUE TITLE
New Moving Head Effect Grid doesn't resize correctly. 

### ISSUE THREAD

**Issue by AGFazio** [xLightsSequencer/xLights#4834]
The positioning grid for the new moving head effect does not resize correctly when expanding the effect settings window. It gets larger whether you upsize or downsize the window. 

Works correctly in 2024.15 . Started in 2024.16

**To Reproduce**
Open new sequence.
Add moving head effect to moving head on timeline.
Try to resive the effect settings window.

**Expected behavior**
Positioning grid should resize to stay within constraints of the effect settings window.

**Versions (please complete the following information):**
 - OS: Windows 11 Home
 - xLights version 2024.16 - 2024.16.2  

![Screenshot 2024-09-26 085218](https://github.com/user-attachments/assets/a52987b2-6b61-4f66-b714-12d33eec3471)

**Comment by derwin12** [comment]
That grid is all hard coded in sizing. It stays the same for me ..
![image](https://github.com/user-attachments/assets/c82aa12c-56d3-4ffd-9eef-a61c9dced5c1)

**Comment by cybercop23** [comment]
I think this was fixed (somehow - didn't see anything specific) in 17

**Comment by AGFazio** [comment]
Still happens. Worked correctly in 2024.17. After in nightly still gets larger when resizing window up or down, the grid grows.

**Comment by cybercop23** [comment]
> Still happens. Worked correctly in 2024.17. After in nightly still gets larger when resizing window up or down, the grid grows.

hmmm.. so it works for Daryl but not for you, and it worked on 17. What happens if you go back to 17, does it go back to working.

**Comment by AGFazio** [comment]
> hmmm.. so it works for Daryl but not for you, and it worked on 17. What happens if you go back to 17, does it go back to working.

Yes. If I go back to 17 all is good. On nightly grid grows as you enlarge or shrink window.

**Comment by Chadskeys** [comment]
I also have this same issue!  Incredibly frustrating and hard to use the moving head effect when you can only see a blown up portion of the upper left hand side of the grid.  No sliders are visible and when you try to expand the window to see everything, it makes it worse, not better.

**Comment by jeremypoling** [comment]
Still seeing this problem in 2025.05 in Windows 10 machine.

**Comment by AGFazio** [comment]
It's your screen resolution and how it reacts with wx widgets in xlights. From what I've been told it's not going to change. Just reduce your screen resolution.

**Comment by jeremypoling** [comment]
> It's your screen resolution and how it reacts with wx widgets in xlights. From what I've been told it's not going to change. Just reduce your screen resolution.

The resolution did not change the issue. The cause of this problem appears to be the scale percentage the display is set to. If you  increase the scaling past 100%, the grid changes size.

**Comment by computergeek1507** [comment]
I assume it is a rounding/scaling issue when using the window size. I run at 150% I will see if I can reproduce it

**Comment by AGFazio** [comment]
FIxed in 2026.09
